### ISSUE TITLE
Скрипт предварительной обработки текста

### ISSUE THREAD

**Issue by capricorn2001** [vantu5z/RHVoice-dictionary#100]
Хочу предложить внести свой скрипт в пакет. Конечно он исправляет чтение далеко не во всех случаях, но во многих. Как оказалось, скрипт на языке Python работает намного быстрее, чем редактор SED. В настоящее время продолжаю его пополнять и улучшать.
Скрипт считывает текст из файла /tmp/clip.txt и в него же записывает результат обработки.

**Comment by vantu5z** [comment]
Я только за. Там можно будет запиливать правила с дефисами и знаками препинания.

**Comment by capricorn2001** [comment]
Как понимаю, поместишь его в папку tools?
Если не против, я буду редактировать скрипт в пакете напрямую сам.
Ссылку не буду тут дублировать - она в соседней теме.

**Comment by vantu5z** [comment]
Да, думаю пока в тулз положим, давай ты последнюю версию сам и положишь :)
Насчет редактироыания, напрямую редактируй без проблем. Если уверен в правке можешь и остальное так редактировать, тебе так даже проще будет - сделал правки, pull чтоб обновить, commit и push.
Кстати ты из консоли работаешь или какой софт используешь типа smartgit, gitg?
Я smartgit'ом пользуюсь - довольно удобно.

**Comment by capricorn2001** [comment]
Я из браузера редактирую. 
Скрипт положу, только пока неясность: надо, чтобы он был исполняемый. Сейчас буду смотреть.

**Comment by vantu5z** [comment]
@capricorn2001, посмотри в ветку templates_mod.
Может лучше так сделать? Отвязываемся от чтения файла и передаём нужный текст напрямую в функцию, а она нам возвращает обработанный текст.
Её можно вызывать из другого скрипта, пример в тесте.
Кстати на счёт теста, как думаешь нужен?

**Comment by capricorn2001** [comment]
@vantu5z, будешь смеяться, но я не понял вопроса... :) О Питоне я знаю почти ровно столько, сколько вложено в скрипт. Фактически, учусь языку, сочиняя скрипт. Поясни, будь добр, что такое ветка templates_mod. Вообще я за любое улучшение скрипта, т.к. он совершенно коряво слеплен.
На второй вопрос не могу ничего ответить по той же причине.

**Comment by vantu5z** [comment]
Извини, попробую объяснить :)
Branch (ветка) - своеобразное ответвление от основной разработки проекта, например для внедрения новой функции или чего-то ещё. Там можно экспериментировать не боясь поломать основную ветку "master".
Между ветками можно переключаться. Слева вверху есть выпадающее меню "branch: master", там можно выбрать нужную ветку.
Там то ты и увидишь изменённый "templates.py" и "test_templates.py". В истории коммитов можешь посмотреть, что изменилось.
Я тоже не знаток Питона и возможно делаю, что-то не то (может нужны классы или нечто подобное), но идея в том чтобы templates.py содержал только алгоритм обработки текста и не завязывался на конкретный файл для получения текста. Я оформил это в виде функции которую можно вызывать передавая ей текст и в ответ получая от неё обработанный текст.

Кстати недавно наткнулся на интересную хаутушку по git, на пальцах объясняют как и что устроено, так для общего развития: 
https://githowto.com/ru

**Comment by capricorn2001** [comment]
Теперь понял.
Я не против модификации скрипта. Как его интегрировать, тебе виднее. Я, например, прикрутил RHVoice к speech-dispatcher'у, но никак его (speech- dispatcher) не использую. Если для проекта удобнее оформить обращение к скрипту как вызов функции, могу сделать - дай знать.
Что касается классов  в Питоне, то до этой главы учебника я ещё не дошел :)
Что касается test_templates, определённо может пригодиться.

**Comment by vantu5z** [comment]
Немного доработал templates.py. Посмотри, если нет нареканий или предложений, то перенесу в "master" и удалю ветку "templates_mod".

**Comment by vantu5z** [comment]
Кстати, а почему не охвачены, например "2016 г." или "2016-й г." - год не раскрывается.

**Comment by vantu5z** [comment]
Добавил изменения из PR #109 в "templates_mod" коммит: 9113d8ce4a162fdf1765c9e6eceb326f10a4745f

**Comment by capricorn2001** [comment]
Переноси - буду править этот вариант.
"2016 г." и "2016-й г." - упустил, сделаю.
И спасибо за ссылку.

**Comment by vantu5z** [comment]
Перенёс коммит 10330217d9c1890de099ecb629817311d17c8e73

**Comment by vantu5z** [comment]
Появилась проблема с точкой в конце текста. Она в каких-то случаях добавляется, а в каких-то нет.

**Comment by capricorn2001** [comment]
С правкой шаблона согласен. Забавно: как-то раз попробовал конструкцию "(|...), т.е. с пустым вариантом - не получилось. Стал избегать в дальнейшем. А оно работает, оказывается - спасибо. Теперь надо будет посмотреть другие шаблоны на предмет упрощения.
Отсутствия точки в конце текста пока не замечал - возможно, зто из-за того что шаблон перенёс в начало. Верну.
Долго пытался сделать проверку всех шаблонов в одном цикле - не вышло. сделаю два.
Насчёт сокращений числительных: сначала просто добавлял к цифре соответствующее количество нулей, потом приравнял такие сокращения к единицам измерения. Не уверен, что стало изящнее, но вроде работает.
