### ISSUE TITLE
Не по теме

### ISSUE THREAD

**Issue by capricorn2001** [vantu5z/RHVoice-dictionary#212]
В AUR'е, похоже, "осиротел" пакет _mailru-cloud_ - даже ссылка ведет на страницу 404. Я отредактировал PKGBUILD и поместил ссылку в комментариях. Пожалуй, даже взялся бы вести пакет. Но 2 "но": 1) у меня система только i686, не могу проверить для x86_64, 2) слишком мало опыта - не знаю, что и как. А пакет, полагаю, нужный. 
Какие-нибудь соображения по этому поводу?

**Comment by vantu5z** [comment]
Да, совсем не по теме :)
1. Как вижу ответственный ReNoM.
2. Пакет не так уж давно обновлялся, возможно ответственный занят чем-то другим и позже обновит пакет в соответствии с твоими изменениями.
3. Для начала свяжись с ответственным, если не получится, то подавай заявку и исправляй пакет, и если он действительно востребован, то тебя поправят (заодно посмотришь, как поддерживать пакеты).
4. Я им не пользуюсь, так что на счёт востребованности судить не могу.

**Comment by capricorn2001** [comment]
ОК. Спасибо. Тему закрываю.
