### ISSUE TITLE
Использование pymorphy2

### ISSUE THREAD

**Issue by vantu5z** [vantu5z/RHVoice-dictionary#215]
@capricorn2001, привет!
Наткнулся тут на днях на pymorphy2. Посмотри, может оно пригодится тебе для разработки templates. ;)

**Comment by capricorn2001** [comment]
@vantu5z, приветствую!
Спасибо, посмотрю :)

**Comment by vantu5z** [comment]
Для использования нужно установить:
pymorphy2
pymorphy2_dicts
pymorphy2-dicts-ru
dawg

**Comment by capricorn2001** [comment]
Не уверен в необходимости стороннего словаря - существительных, которые используются с числительными, по моим впечатлениям не так много. Даже мой словарь во многом избыточен. Это не значит, что я возражаю против данной функции, я предпочел бы сохранить обе возможности - pymorphy2 и свой компактный словарик. Что скажешь?

**Comment by vantu5z** [comment]
Да, я оставляю обе возможности.
Это не совсем словарь, а анализатор слов (и даже отсутствующих в словаре).
Работает вроде как шустро.

Попробую перевести слова из твоего словаря в новый формат. Как раз с помощью этой библиотеки, она умеет определять начальную форму слова и склонять его.
