### ISSUE TITLE
"Морской" глюк

### ISSUE THREAD

**Issue by capricorn2001** [vantu5z/RHVoice-dictionary#216]
Похоже, во всех числах и падежах прилагательное "морской" читается с ударением на первый слог независимо от того, что указано в словаре.

**Comment by vantu5z** [comment]
У меня вроде всё норм с ним.

**Comment by capricorn2001** [comment]
Возможно, различие оттого, что у нас в разное время скомпилирована программа. Я время от времени ее переустанавливаю, чтобы включить последние исправления. Последний раз обновил в середине апреля. До этого был другой глюк: в словах, оканчивающихся на -ись движок удваивал "и", получалось что-то вроде "опиралиись". Теперь у меня такого не наблюдается.

**Comment by capricorn2001** [comment]
Чудеса. Теперь и уменя слово "морской" читает правильно...

**Comment by capricorn2001** [comment]
**vantu5z** , будь добр, проверь, как оно читает слово "кинозвезде". Я у себя внес исправление в словарь, но если у тебя произносит правильно, отменю.

**Comment by zstanecic** [comment]
Один вопрос:

Как у вас RHVoice читает слово радио?У меня оно читает как ра́диа, с 
редукцией второй степени.

можно ли сделать правку в словарь, чтобы слово радио читалось как ра́дио́

то есть чтобы о не было редуцированное в конце?


W dniu 13.05.2018 o 10:26, capricorn2001 pisze:

**Comment by vantu5z** [comment]
да, есть проблемы:
кинозвезде - кинозвЁзде
радио - рАдиа

**Comment by capricorn2001** [comment]
Исправил "кинозвезду" и попытался исправить "радио": внес в словарь правило "радио=р+ади+о". Но, боюсь, не намного улучшил :) **vantu5z,  zstanecic ,** оцените.
