### ISSUE TITLE
Определение падежа + Рефакторинг

### ISSUE THREAD

**Issue by vantu5z** [vantu5z/RHVoice-dictionary#217]
Я тут подумал вынести определение падежа, рода, числа в отдельный класс. Основан будет на том словаре который уже есть, но немного в другом формате с описанием одного слова в разных формах, что упростит его пополнение.
Использоваться будет в виде:
`words.get_gender('слово')` -> мужской / женский 
`words.get_case('слово')` -> [список совпавших падежей] например  [0, 1, 0, 1, 1, 0]
<br>
Буду рад услышать предложения, а также пожелания к необходимым запросам к этому классу.
Через пару дней покажу первый вариант.

**Comment by capricorn2001** [comment]
В принципе "за". С пополнением однозначно станет проще, да и структура будет выглядеть лучше. Пока не представляю, как приспособить к обработке шаблонрв - я очень мало имел дело с классами, ориентируюсь с трудом.
Еще вот. Обработка текстов идет быстро, но пропускать их через все шаблоны подряд не оптимально. Скажем, проверять, присутствует ли число + г./гг. и, только если присутствует, запускать соответствующие шаблоны. Не знаю, стот ли игра свеч - конструкция точно усложнится, а будет ли выигрыш в скорости - вопрос.

**Comment by vantu5z** [comment]
Добавил ветку `check_words_form`, посмотри.
Теперь нужно подумать над необходимыми запросами и оптимизацией.
Ну и если приживётся, нужно переносить словарь в новый формат.

По поводу пропуска через не все шаблоны, пока не очень понимаю, как это реализовать.

**Comment by capricorn2001** [comment]
Посмотрел файлы пока в броузере. Ищу информацию, как клонировать новую ветку :) Как-то привычнее у себя на компе разбираться.

**Comment by vantu5z** [comment]
git fetch должен все подтянуть.
А дальше git checkout <имя ветки>.

**Comment by vantu5z** [comment]
Пытался применять к правилам, иногда получается более громоздко. А где проверки с модификациями слова [:-2] вообще мрак :)

**Comment by capricorn2001** [comment]
Спасибо, клонировал. Боюсь, что не скоро разберусь, что к чему - программист из меня... :)

**Comment by vantu5z** [comment]
Ну там вроде не сложно, если что не понятно спрашивай ;)

**Comment by capricorn2001** [comment]
Я чего-то глобально не улавливаю :) от слова "туплю"
>>> from words_forms import *
>>> Words.get_attr('автобус')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_attr() missing 1 required positional argument: 'word'

**Comment by vantu5z** [comment]
```
from words_forms import *
# для начала нужно создать экземпляр с которым работать
w = Words()
# и уже к нему обращаться
print(w.get_attr('автобус'))
```

При создании экземпляра вызывается его инициализация `def __init__(self)`, где создаются три экземпляра класса WordsForms с загрузкой словарей:
```
self.muz = WordsForms(words_muz.words, M_GENDER)
self.zen = WordsForms(words_zen.words, Z_GENDER)
self.sre = WordsForms(words_sre.words, S_GENDER)
```

**Comment by vantu5z** [comment]
Применил ко всем правилам.
Даже и не знаю, местами сложно читаемо получилось.

**Comment by capricorn2001** [comment]
Да и раньше не особо легко читалось - сам теперь порой не понимаю, чего наваял... Вот что значит, начинать изучение программирования с Бейсика.

**Comment by vantu5z** [comment]
Да, это будет немного затруднительно.

**Comment by vantu5z** [comment]
Перевел словарь в новый формат.

**Comment by capricorn2001** [comment]
Пытался синхронизировать ветку. Накосячил, как обычно.
```
git status
На ветке check_words_form
Ваша ветка опережает «origin/check_words_form» на 23 коммита.
  (используйте «git push», чтобы опубликовать ваши локальные коммиты)

нечего коммитить, нет изменений в рабочем каталоге
```
Пребываю в задумчивости.

**Comment by vantu5z** [comment]
`git pull` не помогает?
Может из-за того, что я делал `rebase` и `push --force`, чтобы внести изменения из мастера.

**Comment by capricorn2001** [comment]
Я делал:
```
git fetch
git pull
```
(Выдал несколько конфликтов).
`git add tools/preprocessing/*`
Еще сделал git commit зачем-то.

**Comment by capricorn2001** [comment]
Наверно проще снести всю папку и заново всё загрузить :)

**Comment by vantu5z** [comment]
Погоди пару минут, я сейчас последние изменения применю. И потом синхронизируешься :)

**Comment by vantu5z** [comment]
Всё, я закончил. Можешь обновляться :)

**Comment by capricorn2001** [comment]
Обновил.

**Comment by capricorn2001** [comment]
> Не установлен "pymorphy2".Определение аттрибутов слова будет вестись по словарю.
> ВНИМАНИЕ! неверное преобразование: "в течение 21 сек" -> "в течение двадцати одного секунды."                 должно быть: "в течение двадцати одной секунды."
> ВНИМАНИЕ! неверное преобразование: "1 царя" -> "1 царя."                 должно быть: "одного царя."
> 
> Пройдено проверок: 44 из 46
Попробую разобраться.

**Comment by capricorn2001** [comment]
> Введите текст:
> 21 сек
> Обработанный текст:
> 21 секунда.

**Comment by vantu5z** [comment]
нашел косяк, сейчас исправлю

**Comment by vantu5z** [comment]
Еще вопрос по поводу буквы Ё в словарях.
Раньше все слова были с Е, а теперь с Ё. Как думаешь вернуть Е или добавить дубликаты слов?

**Comment by capricorn2001** [comment]
Если возможно, думаю, лучше оба варианта. Если оставить один, то я бы оставил Е - чаще употребляют.

**Comment by capricorn2001** [comment]
(кило-, мега-, гига-)парсекОВ.

**Comment by vantu5z** [comment]
Немного доработал определение падежа. Проверь теперь.
И поподробней напиши про `(кило-, мега-, гига-)парсекОВ`.

**Comment by capricorn2001** [comment]
Пока не обнаруживаю ошибок.
В words_muz.py неправильная форма род. пад. мн. ч.: парсек. Должно быть парсеков.
1 парсек, 10 парсеков.
И, соответственно, кило-, мега-, гига-.

**Comment by vantu5z** [comment]
поправил 2f8217b057b8bbbbe9755a9a7c0b01460d5d4904

**Comment by capricorn2001** [comment]
Такая мысль - довести до логического конца разделение: в файле templates.py у нас шаблоны и функции: не стоит ли выделить функции в отдельный файл, а, возможно, txt_prep() вообще сделать отдельным файлом? Рефакторинг так рефакторинг...

**Comment by vantu5z** [comment]
Я тоже об этом подумываю :) Как тебе такой вариант?
`templates.py` - шаблоны
`functions.py` - функции
`words_forms.py` - разбор слов
`dict\words_muz.py...` - словари
`main.py` - основной модуль c `txt_prep()` (наверно стоит как-то по-другому назвать)

**Comment by vantu5z** [comment]
Эх!
Наворотил всякого-разного, можешь проверить не забыл ли я чего?

**Comment by capricorn2001** [comment]
Предлагаю, как только новый вариант будет готов, перенести его в ветку master, чтобы упростить редактирование шаблонов..

**Comment by capricorn2001** [comment]
По-моему, нормально. Со временм может что-то проявиться, но пока порядок.

**Comment by vantu5z** [comment]
Cлил всё в мастер.

**Comment by capricorn2001** [comment]
git status показыввает новые файлы и советует:

> Ваша ветка обновлена в соответствии с «origin/master».
> 
> Изменения, которые будут включены в коммит:
>   (используйте «git reset HEAD <файл>…», чтобы убрать из индекса)

Мне их перечислить в этой команде?

**Comment by vantu5z** [comment]
Как у тебя это получается))))
посмотри `git reset -h`, думаю можно сделать `git reset --hard`, если нечего терять.

**Comment by capricorn2001** [comment]
Стоп. Там в списке файлы из tools/preprocessing/dict/__pycache__/

**Comment by vantu5z** [comment]
хм.. он их не должен видеть, каталог(и) `__pycache__`  включен в `.gitignore`

**Comment by capricorn2001** [comment]
В люббой директории не должен видеть?

**Comment by vantu5z** [comment]
Ну да. У меня не видит.

**Comment by capricorn2001** [comment]
Удалю из tools/preprocessing/dict и сделаю git rm.

**Comment by capricorn2001** [comment]
Вроде порядок.

**Comment by vantu5z** [comment]
Думаю ветки стоит создавать, когда изменения неоднозначные или глобальные.
А так, смотри сам, попробовать можно. Если запутаемся или не понравиться вернёмся к старой схеме :)
Ну и сливать в master тоже можешь сам, как протестишь изменения ;)

**Comment by capricorn2001** [comment]
Хорошо. Буду вносить изменения в мастер :)
