### ISSUE TITLE
Please define the license

### ISSUE THREAD

**Issue by yurivict** [vantu5z/RHVoice-dictionary#220]
Ports and packages need license to be distributed with.

**Comment by vantu5z** [comment]
@yurivict, can you help us to choose license? I think it should be free as possible. Also we should listen @capricorn2001 opinion, maybe he have some ideas already.

@yurivict, не могли бы Вы помочь нам с выбором лицензии? Я думаю она должна быть свободной насколько это возможно. Также нужно узнать мнение @capricorn2001, может быть у него уже есть идеи на этот счёт.

**Comment by capricorn2001** [comment]
I have no idea about this item.
