### ISSUE TITLE
Некорректно работает CountRule_36

### ISSUE THREAD

**Issue by capricorn2001** [vantu5z/RHVoice-dictionary#225]
Пока исключил это правило из-за непонятного срабатывания.
_18 день -> восемнадцатый день_: существительное мужского рода единственного числа в именительном/винительном падеже, то есть **attr.have([M_GENDER], False, [0])** должно быть истинно. Тут всё правильно.
_18 мегаватт_ не должно обрабатываться при совпадении с формой множественного числа в родительном падеже, то есть если **attr.have([M_GENDER], True, [1])** тоже **истинно**. Но в этом случае **attr.have([M_GENDER], True, [1])** почему-то **ложно**.
Условие
```
    if (attr.have([M_GENDER], False, [0])
        and not attr.have([M_GENDER], True, [1])):
        ...
```
не работает во второй своей части.

**Comment by vantu5z** [comment]
Попробуй сейчас, после исправления (65a6e2ebf3be8160b76eb5788d5232930fad0263) должно работать.

**Comment by capricorn2001** [comment]
Работает.
Заменил номер правила CountRule_36 на CountRule_38.
