### ISSUE TITLE
Местный падеж

### ISSUE THREAD

**Issue by capricorn2001** [vantu5z/RHVoice-dictionary#226]
Столкнулся с этим, уточняя CountRule_4. Некоторые существительные имеют особую форму в предложном падеже, которую иногда выделяют в отдельный падеж — местный: в лесу, на полу, в полку и т.д.
Можно решить по-разному.
Создать список соответствующих слов (предпочитаю данный вариант):
(..., 'лесу', 'полку', 'саду').
Добавить ещё одну форму в список словаря:
('полк', 'полка', 'полку', 'полок', 'полком', 'полке', 'полку').
Вопрос в том, как это решено в pymorphy2 и решено ли?
Пока буду делать предварительно с отдельным списком слов-исключений

**Comment by vantu5z** [comment]
Не очень понял в чем проблема?

**Comment by vantu5z** [comment]
В pymorphy2 вроде как есть поддержка местного падежа (loc2).

**Comment by capricorn2001** [comment]
В общем проблемы нет - я добавил несколько строк в правило. У меня  pymorphy2 нет, поэтому не знаю, как его приспособить.
