### ISSUE TITLE
[CountRule_39] 8 марта -> восьмая марта

### ISSUE THREAD

**Issue by vantu5z** [vantu5z/RHVoice-dictionary#230]

**Comment by capricorn2001** [comment]
Не понял.

> Не установлен "pymorphy2".
Определение атрибутов слова будет вестись по словарю.
Пройдено проверок: 64 из 64
Введите текст:
8 марта
Обработанный текст:
восьмого марта

**Comment by vantu5z** [comment]
Видимо из-за pymorphy2
```
rhvoice_say -d "8 марта"
Сработало правило: CountRule_39
     найдено: "<re.Match object; span=(0, 7), match='8 марта'>"
    заменено: "восьмая марта"

восьмая марта
```

**Comment by vantu5z** [comment]
Добавил в правило ещё один костыль по аналогии
bb75cf1ceb47d782f7f6b65939d6cbb38aafe21a

**Comment by capricorn2001** [comment]
Предлагаю немного переупорядочить обработку, чтобы к моменту проверки этим правилом уже было обработано. Надеюсь, других подобных косяков в pymorphy2 нет, а если есть, вернем твое решение.
Еще хочу переименовать CountRule  в CardinalRule и OrdinalRule соответственно для порядковых и количественных числительных.
Твое мнение?

**Comment by vantu5z** [comment]
Действуй, посмотрим, что получится :)

**Comment by capricorn2001** [comment]
Сднлано.
Будь добр, проверь, как теперь "8 марта" читается. Если OK, то можно закрыть тему.
Я еще поправлю чтение праздников с большой буквы: 8 Марта, 1 Мая и 9 Мая.

**Comment by vantu5z** [comment]
Спасибо! Проверил, вроде работает.
