### ISSUE TITLE
test_templates.py -d

### ISSUE THREAD

**Issue by capricorn2001** [vantu5z/RHVoice-dictionary#232]
У меня перестал работать скрипт test_templates.py в режиме debug. Выдает:

> Traceback (most recent call last):
>   File "/home/myhomedir/Files/Git/RHVoice-dictionary/tools/test_templates.py", line 103, in <module>
>     text = text_prepare(txt[0], debug)
>   File "/home/myhomedir/Files/Git/RHVoice-dictionary/tools/preprocessing/text_prepare.py", line 67, in text_prepare
>     for sample in stress_marker_samples(stress_marker):
>   File "/home/gena/Files/Git/RHVoice-dictionary/tools/preprocessing/templates.py", line 1623, in stress_marker_samples
>     ('а́', marker + 'а'),
> TypeError: unsupported operand type(s) for +: 'bool' and 'str'

Если это не только у меня, помоги разобраться.

**Comment by vantu5z** [comment]
Исправлено в комите: 33b2533722cc27543dbb5c35749d4c093bc1b18d.

**Comment by vantu5z** [comment]
Кстати правила с расстановкой ударения символом в тесте не проверяются.

**Comment by capricorn2001** [comment]
Спасибо.

**Comment by capricorn2001** [comment]
Проходит «штатные» проверки, но при попытке проверить произвольную фразу с ключом -d выдает ошибку.

**Comment by capricorn2001** [comment]
Поправил (надеюсь). [4cb6016a](https://github.com/vantu5z/RHVoice-dictionary/commit/4cb6016a135484f9f0f98bbebaa85420c3d54cc6).
