### ISSUE TITLE
разница между именем существительным единственного числа и множественного числа

### ISSUE THREAD

**Issue by zstanecic** [vantu5z/RHVoice-dictionary#27]
можно ли сделать что бы синьтезатор делал разницу помежду именем существительным ’д+ома и дом+a? одное имя существителное в единственном числе в прымере Я дома.. а в другом примере Это наши дома

**Comment by vantu5z** [comment]
Не знаю как это реализовано в самом синтезаторе, но сформулировать правило для исправления ударения в принципе возможно, но правда не во всех случаях.

По-умолчанию синтезатор делает ударение на "дом+а", но в стандартном словаре (example.txt) указано правило, которое переносит ударение на первый слог:
дома=дома/1

В нашем словаре для "дома" уже есть несколько правил:
*{и,ы}е дом+а
в дом+а

Т.е. "я дома" он должен говорить правильно, если у вас подключен стандартный словарь.

По поводу "наши дома" вариант неоднозначный, т.к. в этом словосочетании может использоваться как единственное, так и множественное число и ударение будет изменяться.
Подобрать сходу словосочетании в которых "дома" будет только во множественном числе у меня не получается, если есть предложения всегда рады их услышать.

Спасибо за участие.

**Comment by zstanecic** [comment]
проблема лежит в том, что  я слышу рхвоице как и его произношение как 
/дама/.
и он не делает никакую разницу.

W dniu 06.02.2016 o 08:41, Ivan pisze:

**Comment by zstanecic** [comment]
У меня подключен только ваш словарь.

W dniu 06.02.2016 o 08:41, Ivan pisze:

**Comment by vantu5z** [comment]
Поправил. Попробуйте теперь.
