### ISSUE TITLE
Ударение в слове "задал"

### ISSUE THREAD

**Issue by capricorn2001** [vantu5z/RHVoice-dictionary#37]
Полагаю, это правило можно исключить: в словарях указывается ударение либо на первый слог, либо допускается и на первый, и на второй слог.
https://slovari.yandex.ru/%D0%B7%D0%B0%D0%B4%D0%B0%D1%82%D1%8C/%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5/
(То же относится и к слову "пробыл".)

**Comment by vantu5z** [comment]
Поддерживаю. Поправишь? У меня работа навалилась просто, времени совсем нет..

**Comment by capricorn2001** [comment]
Сделаю. Уберу оба слова.
