### ISSUE TITLE
расширить словарь

### ISSUE THREAD

**Issue by linvinus** [vantu5z/RHVoice-dictionary#47]
вот тут есть большой словарь произношения
http://golosknigi.com/page3.html
можно адаптировать под формат rhvoice если заменить записи вида 

`криологи*=ъъкриолQогиъъ`
на
`(к=ъък)риол+ог(и=иъъ)*`

например как нибудь так
`sed 's/\(ъъ\(\w\)\)/\(\2\=ъъ\2\)/ig;s/\(\(\w\)ъъ\)/\(\2\=\2ъъ\)/ig;' /tmp/rhvoice/Sapi5_RHvoice_2.dic`

**Comment by vantu5z** [comment]
Спасибо, я тоже на него натыкался.
Но вопрос стоит в том, чтобы не просто адаптировать, а ещё и проверить каждое правило, т.к. Rhvoice часть слов уже читает правильно.
Например из Sapi5_RHvoice_2.dic:
 криологи*=ъъкриолQогиъъ - читает как криол+огия
 Арбат*=ъъАрбQатъъ - читает как Арб+ат, Арб+ату

Если у вас есть желание и возможность адаптировать и проверить нужность каждого правила будем очень признательны. Ещё раз спасибо за участие.

**Comment by linvinus** [comment]
Вот тут есть  большой словарь с ударениями http://hci.nw.ru/index.php?id=7 "Файлы модели языка"  там dic_full.txt 56Мб текста в utf8
пример
`абсолюти!рованной
абсолюти!рованную
`
к сожалению я занят другими проектами, поэтому кроме как информацией больше помочь ничем не могу пока.

**Comment by velmyshanovnyi** [comment]
> Вот тут есть большой словарь с ударениями http://hci.nw.ru/index.php?id=7

файла уже там нет ((
