### ISSUE TITLE
Вынести названия улиц в отдельный файл

### ISSUE THREAD

**Issue by vantu5z** [vantu5z/RHVoice-dictionary#54]
Предлагаю вынести раздел с названиями улиц в отдельный файл.

**Comment by capricorn2001** [comment]
Можно попробовать, хотя не уверен.

**Comment by vantu5z** [comment]
Я с точки зрения пополнения и обработки Вики - в истории будет видно по каким буквам обработано и прочие правки. Ну и думаю это будет плюсом к мобильной версии, если используется для навигатора - можно подключить только улицы без лишнего словаря.

**Comment by capricorn2001** [comment]
В таком случае, я "за". Идея выборочного подключения нравится - скажем, во время установки выбирать нужные словари (когда/если они будут). Во всём, что касается мобильного применения, помочь не смогу - пользуюсь исключительно десктопом.

**Comment by vantu5z** [comment]
Сделано cfb787a5fc6a6d27329aa2e1a1d12b45c57cf353
