### ISSUE TITLE
Что будем делать с выходом новой верии RHVoice?

### ISSUE THREAD

**Issue by vantu5z** [vantu5z/RHVoice-dictionary#70]
Что-то меня мысль посетила.
Вот пилим пилим мы словарик, а с выходом новой версии движка половину правил в нём учтут.
Как перепроверить правила?

Как вариант написать небольшой скриптик, который делает из словаря список слов (словосочетаний) без указания ударения (исправления) и записывает его в файлик. Потом этот файлик скармливается другому скрипту, который по нажатию читает первое слово и ждёт реакции (правильно / неправильно / прочитать ещё раз), по результатам реакции составляются новые списки: 1. на удаление, 2. на включение. Дальше либо вручную корректируется словарь, либо придумать автоматизацию для этого.

Эту штуковину можно будет также использовать для проверки сторонних словарей, предварительно подготовив их.

**Comment by GFOXSH** [comment]
Верная мысль, она меня тоже много раз посещала. Что же я хочу сказать по этому поводу: Последнее обновления модуля распознования русского языка датируется 3 октября 2014. По сему не думаю, что нам следует скоро ожидать обновлений. Но, если оно выйдет, то действительно придется перекапывать весь словарь заново...

**Comment by vantu5z** [comment]
Добавил скрипт на питоне для проверки списка фраз из файла. commit 74074f4
По результатам выполнения создаются 3 файла: 
1 - с остатками фраз для проверки
2 - с хорошими фразами
3 - с плохими фразами

**Comment by paulvi** [comment]
@vantu5z Open issue in https://github.com/Olga-Yakovleva/RHVoice/issues or find other way to contact Olga, make friends and discuss
