### ISSUE TITLE
Ребятушки! Как воевать с числительными и датами?

### ISSUE THREAD

**Issue by alexandr-shilin** [vantu5z/RHVoice-dictionary#74]
Подскажите, как превратить "1956 г." в "одна тысяча девятьсот пятьдесят шестой год", например?

**Comment by vantu5z** [comment]
Как вариант, обрабатывать строку перед произношением. Вычислять как-то это выражение. Например мы выбрали из строки "1956 г."
Теперь выделим число: 1956
Узнаем склонение по двум последним цифрам "56" (год, года, лет)
Потом обнулим последнюю цифру: 1950
Видимо надо преобразовать последнюю цифру в слово: 1-один, 2-второй, 3-третий...
И соберём произносимый текст в строку: 1950 + шестой + год

**Comment by capricorn2001** [comment]
Я сделал файл шаблонов для предварительной обработки редактором **sed** и небольшой bash-скрипт, который при запуске обрабатывает текст из буфера и передает его голосовому движку. Если интересно, выложу. Только видимо надо будет снабдить комментариями, т.к.  шаблонов много - почти тысяча, и не все они отработаны.

**Comment by capricorn2001** [comment]
Добавил комментарии.
Скрипт: [http://pastebin.com/76VDRXRE](url)
Файл шаблонов: [http://pastebin.com/yknGzP2C](url)
Пользоваться несложно: выделяем текст и запускаем скрипт специально сделанной кнопкой или хоткеем. Кое-какие сомнительные шаблоны закомментированы, также некоторые слишком специфические, напр. буквы греческого алфавита. Думаю, на Python'е было бы лучше. Когда/если освою, попробую сделать.
