### ISSUE TITLE
Географические и т.п. названия

### ISSUE THREAD

**Issue by capricorn2001** [vantu5z/RHVoice-dictionary#84]
А вот куда вносить названия рек? Подозреваю, что могут потребоваться правила для морей, озёр,  гор, стран, звёзд, планет, астероидов.

**Comment by GFOXSH** [comment]
Добрый день! Извините, что последнее время не захожу сюда. Работаю над переносом SDL игр на Android, но сейчас это не имеет значения. Я предлагаю сменить словарь улиц на словарь географических названий и туда сбрасывать все названия.

**Comment by vantu5z** [comment]
Я думаю стоит пока оставить словарь "улиц и городов", туда же думаю можно складывать и названия стран. Он пригодится для использования с навигатором и в нём названия астероидов думаю ни к чему.
Словарь имён переименовать в "person_names" или просто в "persons".
И создать ещё один словарь с названиями "names" или "geo_names", куда и складывать все названия.
Как вам такой вариант?

**Comment by capricorn2001** [comment]
Может быть, так?

- _locations_ - названия стран, населенных пунктов, улиц

- _person_names_ - имена людей

- _names_ -  прочие названия

**Comment by vantu5z** [comment]
Произвёл реструктуризацию словарей.
commits:
ff771a015e0ca9def19c8b31c5ca7b6eb009dbd0
077e5d29b821dfa1a9fff3762470f05a4d3180c8

**Comment by capricorn2001** [comment]
Закрываю тему.
