### ISSUE TITLE
Отдельные символы (например греческие)

### ISSUE THREAD

**Issue by vantu5z** [vantu5z/RHVoice-dictionary#87]
В рассылке RHvoice поднялась тема по чтению греческих символов:
http://tiflo.info/pipermail/rhvoice-users_tiflo.info/2016-July/thread.html

@capricorn2001 сделал скрипт для их обработки, но это решение не для всех и должно задействовать предобработку текста (до передачи в движок).

В словаре с примерами есть описание, как задать символ его кодом.
Я попробовал и кодом и символом - работает.
Но!
Почему-то у меня не читает эти символы, если они находятся в тексте. Я подумал, что RHvoice считает их пунктуацией (в wiki и конфиг файле есть упоминания об этом), но у меня не получилось заставить его читать символы расположенные в тексте.

Какие будут предложения?
Может это просто у меня что-то с руками :)

**Comment by capricorn2001** [comment]
**vantu5z,** вообще-то, если бы у тебя одного, то я не добавил бы шаблоны для греческого алфавита :)
А пока пытаюсь перевести кое-что на Python (с одновременным его изучением). Сделал замену римских цифр на арабские - очень уж неказисто это получилось в SED.

**Comment by vantu5z** [comment]
Не хочешь создать репозиторий, интересно, что ты там такое творишь, будем вместе изучать. Оно и веселей будет:)

**Comment by capricorn2001** [comment]
Пока ничего почти и нет. И Питон я почти не знаю :) Искал скрипты в интернете, чтоб преобразовывать римские цифры, на Bash ничего не нашел. Попалась функция на Питоне, немного переделал, добавил несколько строк, встроил вызов из скрипта.
[http://pastebin.com/DJEhdcXe](url)
В самом скрипте вызов пока закомментирован.

**Comment by capricorn2001** [comment]
Сделал скрипт на языке Python, обрабатывающий некоторые (пока некоторые) случаи с порядковыми числительными. Постараюсь перенести туда шаблоны, которые у меня выполняет SED.  Вызвать можно из Bash-скрипта, в дальнейшем надеюсь полностью перейти на Python.
http://pastebin.com/8kHSBLeS
Самая большая проблема на данный момент - чудовищный по размерам и структуре кортеж с формами числительных :)
